# Generated by Django 2.1.1 on 2018-12-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_auto_20181225_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
